### ISSUE TITLE
The headers of the NMDC website don't match the products

### ISSUE THREAD

**Issue by mslarae13** [microbiomedata/submission-schema#172]
See screen shot. It throws me off when the text shifts & people tend to struggle to find the submission portal in the products tab.

Website
![Screenshot 2024-01-03 at 9 14 55 AM](https://github.com/microbiomedata/submission-schema/assets/44581429/66ddb8af-a6db-4db3-bc73-223f8cc04506)

Product portals
![Screenshot 2024-01-03 at 9 15 01 AM](https://github.com/microbiomedata/submission-schema/assets/44581429/aa2d37e6-6b76-4085-b3da-5c29608a4cd6)

**Comment by mslarae13** [comment]
Did you determine if this mattered & could/should be done? @pkalita-lbl

**Comment by pkalita-lbl** [comment]
IMO I'm not sure exactly what we'd do here. 

The unavoidable fact is that we're talking about headers on _two different websites_. We are conscious of keeping the _content_ of the menus the same, but as far as the _design_ goes it's hard to divorce the menu from the site it is a part of. For example:

1. The portal site (https://data.microbiomedata.org/) needs to accommodate the login/logout/user info. That will never be a part of the WordPress site (https://microbiomedata.org/). 
2. The WordPress site is based around a fixed-width layout. All the content _including the header_ is constrained to a fixed width which is why you get whitespace to the left of the logo and to the right of the Contact menu. The portal site is based on a full-width layout. That's why there is no whitespace to the left of the logo there or to the right of the login/logout/user info. It would be odd to have a fixed-width header above full-width content or vice-versa.
3. Each site uses a different set of fonts, and the header of each site reflects that.

Those are just some of the obvious difference between the designs of the two sites. There's more subtle stuff, too, that varies between them that's not really worth getting into. The bottom line is: they're never going to be pixel-for-pixel identical.

So what are the complaints? 

> the text shifts

Mainly that's driven by points 1 and 2 above, especially point 2. Because you're going between a fixed-with layout and a full-width layout the degree if shifting you get it _mostly_ determined simply by how wide your browser window is. 

> people tend to struggle to find the submission portal in the products tab

I'm not quite sure what to say about that. Do you have suggestions?

**Comment by mslarae13** [comment]
I think I was referring to text size and font. Not position. Can we make it bigger on the products? 

For finding the "submission portal" button... @ljohnson09 I think you had some feedback on this, in an issue? Do you recall?

**Comment by pkalita-lbl** [comment]
We could try making the font size in the portal header bigger across the board and see if that's better. But I would be extremely wary about making the font size bigger for _only_ the product links. I think that would look unusual.

**Comment by mslarae13** [comment]
> the font size bigger for only the product links
no... I mean make them all match...
About, Product, Community, Resources,Contact ... so they catch the eye better.

**Comment by pkalita-lbl** [comment]
Okay let's try a larger font size in the portal header as a path forward.

**Comment by ljohnson09** [comment]
@mslarae13 We had a couple of users from the user interviews that had trouble getting back to the SP after it rerouted them to the DP after ORCiD log in. But eventually people were able to find the products tab - I think they were mostly thrown off by the new portal.

**Comment by mslarae13** [comment]
> @mslarae13 We had a couple of users from the user interviews that had trouble getting back to the SP after it rerouted them to the DP after ORCiD log in. But eventually people were able to find the products tab - I think they were mostly thrown off by the new portal.

@ljohnson09 this is fixed! https://github.com/microbiomedata/nmdc-server/pull/1275 
Will be in prod at the end of the month
