### ISSUE TITLE
Missing actions in modifications_long.tsv

### ISSUE THREAD

**Issue by bmeluch** [microbiomedata/submission-schema#194]
In rows where the attributes "expected_value" or "preferred_unit" are being modified, the "action" column is left blank. What modification is supposed to be happening here? @pkalita-lbl @turbomam do you remember what the intent was?

Examples
https://github.com/microbiomedata/submission-schema/blob/0b9413915f63bd7fa9be70f32061db49dc422009/sheets_and_friends/tsv_in/modifications_long.tsv#L94

https://github.com/microbiomedata/submission-schema/blob/0b9413915f63bd7fa9be70f32061db49dc422009/sheets_and_friends/tsv_in/modifications_long.tsv#L222

**Comment by pkalita-lbl** [comment]
I don't know enough of the history here to know if that was intentional or not, but in actuality those rows currently do nothing. 

The logs generated by `sheets_and_friends` as it processes the `modifications_log.tsv` file are quite noisy (noisy but also cryptic 🙃), but you can see here on line 3161 of the output of `make all`: https://github.com/microbiomedata/submission-schema/actions/runs/8827491751/job/24234818535#step:7:3162 It says it's processing the slot `extreme_event`, there is no action (`nan`), the target is `expected_value` and the value is `date, string`. The next line down (3162) says `no action for nan` indicating that it didn't do anything for that row ([source](https://github.com/microbiomedata/sheets_and_friends/blob/6f29341f328d66b7af9c690dbff2586963e6a700/sheets_and_friends/modifications_and_validation.py#L168)).

Because there are no LinkML metamodel elements called `expected_value` or `preferred_unit` (unlike, say, `range` or `description` used in other rows), if I had to make a _guess_ I would say those rows were maybe supposed to have the action `replace_annotation` ([source](https://github.com/microbiomedata/sheets_and_friends/blob/6f29341f328d66b7af9c690dbff2586963e6a700/sheets_and_friends/modifications_and_validation.py#L138)). 

So I think two valid paths forward are:

1. Add `replace_annotation` as the action to those rows
2. Remove the rows entirely

Maybe @turbomam could chime in on his preference

**Comment by turbomam** [comment]
Yeah, it looks like I was just confusing the capabilities of a couple of different pieces of software, like `schemasheets`, `sheets_and_friends` and `yq`. `expected_value` and `preferred_unit` are annotation keys, not LinkML features, like @pkalita-lbl said. Even if we did add those, I'm not sure they would show up in the Submission Portal interface. I'll look though that now.

**Comment by turbomam** [comment]
[ammonium_nitrogen](https://microbiomedata.github.io/submission-schema/ammonium_nitrogen)  has an `expected_value` annotation of 'measurement value', but that doesn't show up when you double-click on the 'ammonium nitrogen' column header on a `SoilInterface` Submission Portal screen.

I **think** we can just remove those TSV rows.

**Comment by turbomam** [comment]
Although there is a [`replace_attribute` action](https://github.com/microbiomedata/sheets_and_friends/blob/84d24d74ae7393f117cc5f238cbfbacc2a6d34f1/sheets_and_friends/modifications_and_validation.py#L27)

**Comment by ssarrafan** [comment]
@turbomam @bmeluch not really sure if this is active or not?  Can you please close or move to the next sprint or to the backlog?
